[Variables]
Name1=gitchecker
Action1=ms-powerautomate:/console/flow/run?environmentid=Default-a515e7c4-8cf7-4f97-b23b-96491645f7f0&workflowid=6834c7cc-9fd5-494a-947a-79e6c6a2a99d&source=Other
Name2=social
Action2=http://facebook.com
Name3=videos
Action3=%USERPROFILE%\Videos
Name4=games
Action4=steam.exe
Name5=music
Action5=%USERPROFILE%\Music

Name6=pictures
Action6=%USERPROFILE%\Pictures

Name7=settings
Action7=control.exe

FontFace=#FontFaceLight#
spacing=20
FontSize=23
fontcolor=255,255,255,255
Zoom=1.15
