# PANEL METRICS

[Variables]
Imagedir=C:\Users\primu\OneDrive\Documents\Rainmeter\Skins\WP7\@Resources\Common\Panel\Blank
Overlay=none

Globalblurenable=0
Blurtype=1
Blurcornerradius=0
Padding=5
Win10Blur=none
ColorSkin=30,30,30
ColorSkin2=60,60,60

Opacity=240
Opacity2=240

TextColor=255,255,255
TextColor2=255,255,255


PanelTitleOpacity=255
Shadow=shadow
ItemShadowColor=0,0,0,1
Align=left
Xposition=10
DefaultFontSize=(#Height#/15)
Yposition=5

FontType=Segoe WP Semibold
FontTypeWP=Segoe WP
FontFaceUI=Segoe UI
FontFaceLight=Segoe WP Light
centertextOn=0
Angle=0
PanelTitleOpacity2=1
PanelLabels=1
metric=0
